name: Generate Textures List

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate textures list
        run: |
          npm install
          node generate-textures-list.js

      - name: Commit and push textures list
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Generate textures list'
